name: responsive_property
description: Inspired by Flutter's MaterialStateProperty, gives you a responsive value based on the current screen dimension.
version: 0.0.8
homepage: https://github.com/KevinVan720/responsive_property

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_class_parser: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

